### ISSUE TITLE
Serialization problem

### ISSUE THREAD

**Issue by coolemza** [Flaxoos/flax-ktor-plugins-examples#2]
Your current kotlinx.serialization core version is 2.0.21, while current Kotlin compiler plugin unknown requires at least 1.0-M1-SNAPSHOT. Please update your kotlinx.serialization runtime dependency.

**Comment by Flaxoos** [comment]
Yes, i'm on it, a new version is coming in very soon, you can check out the branch here: https://github.com/Flaxoos/extra-ktor-plugins/tree/kotlin-2-support

**Comment by coolemza** [comment]
can you release beta from this branch? need it badly )

this solution dont work for me https://github.com/Kotlin/kotlinx.serialization/issues/993#issuecomment-984742051

**Comment by coolemza** [comment]
oh did it alrady!

**Comment by coolemza** [comment]
Resolved
